#pragma once

#ifdef USE_ESP32

#include "esphome/core/component.h"
#include "esphome/core/automation.h"
#include "esphome/core/log.h"
#include "esphome/components/text_sensor/text_sensor.h"

#include <WebSocketsClient.h>
#include <HTTPClient.h>
#include <WiFiClient.h>
#include <ArduinoJson.h>

#include <functional>
#include <string>
#include <vector>

namespace esphome {
namespace browser_relay {

static const char *const TAG = "browser_relay";

// ─────────────────────────────────────────────────────────────────────────────
// BrowserRelayClient
// ─────────────────────────────────────────────────────────────────────────────

class BrowserRelayClient : public Component {
 public:
  // ── Configuration setters (generated by __init__.py) ───────────────────
  void set_server(const std::string &server) { server_ = server; }
  void set_port(uint16_t port) { port_ = port; }
  void set_token(const std::string &token) { token_ = token; }
  void set_initial_url(const std::string &url) { initial_url_ = url; }
  void set_width(int width) { width_ = width; }
  void set_height(int height) { height_ = height; }
  void set_auto_connect(bool v) { auto_connect_ = v; }

  void set_url_sensor(text_sensor::TextSensor *s) { url_sensor_ = s; }
  void set_status_sensor(text_sensor::TextSensor *s) { status_sensor_ = s; }

  // Screenshot callback: fires with (jpeg_bytes_ptr, jpeg_length).
  void add_on_screenshot_callback(std::function<void(uint8_t *, size_t)> cb) {
    screenshot_callbacks_.push_back(std::move(cb));
  }

  // ── ESPHome lifecycle ──────────────────────────────────────────────────
  float get_setup_priority() const override { return setup_priority::AFTER_WIFI; }
  void setup() override;
  void loop() override;
  void dump_config() override;

  // ── Public control API ─────────────────────────────────────────────────

  /**
   * Navigate the remote browser to a URL.
   * Must be connected (call connect_session() first or use auto_connect: true).
   */
  void navigate(const std::string &url);

  /**
   * Send a mouse click at browser-viewport coordinates (x, y).
   * button: "left" (default), "right", or "middle".
   */
  void click(int x, int y, const std::string &button = "left");

  /** Scroll by delta_y (positive = down) at the current mouse position. */
  void scroll(int delta_y, int delta_x = 0);

  /**
   * Type a string of characters into the active element.
   * Uses the server-side 'type' message which applies per-key delays.
   */
  void type_text(const std::string &text);

  /**
   * Send a keyboard key by Playwright key name ("Enter", "Escape", "Tab", etc.)
   */
  void key_press(const std::string &key);

  /** Create a new browser session on the server and open the WebSocket. */
  void connect_session();

  /** Close the WebSocket and ask the server to destroy the session. */
  void disconnect_session();

  bool is_connected() const { return ws_connected_; }
  const std::string &session_id() const { return session_id_; }

  /**
   * Return a pointer to the most recent JPEG screenshot buffer and its size.
   * Returns nullptr / 0 if no frame has been received yet.
   * Valid until the next frame arrives.
   */
  const uint8_t *last_screenshot(size_t *out_length) const {
    *out_length = screenshot_buf_.size();
    return screenshot_buf_.empty() ? nullptr : screenshot_buf_.data();
  }

 protected:
  // ── Config fields ──────────────────────────────────────────────────────
  std::string server_;
  uint16_t    port_{8000};
  std::string token_;
  std::string initial_url_{"https://example.com"};
  int         width_{1280};
  int         height_{800};
  bool        auto_connect_{true};

  // ── Sensors ────────────────────────────────────────────────────────────
  text_sensor::TextSensor *url_sensor_{nullptr};
  text_sensor::TextSensor *status_sensor_{nullptr};

  // ── Callbacks ──────────────────────────────────────────────────────────
  std::vector<std::function<void(uint8_t *, size_t)>> screenshot_callbacks_;

  // ── Runtime state ──────────────────────────────────────────────────────
  std::string session_id_;
  bool        ws_connected_{false};
  bool        session_active_{false};
  bool        connecting_{false};
  uint32_t    reconnect_at_ms_{0};
  uint8_t     connect_failures_{0};

  WebSocketsClient ws_client_;
  std::vector<uint8_t> screenshot_buf_;  // Latest decoded JPEG frame.

  // ── Internals ──────────────────────────────────────────────────────────

  /** POST /api/sessions and store the returned session_id. Returns true on success. */
  bool create_session_();

  /** Open the WebSocket to /ws/session/{session_id}?token=... */
  void connect_websocket_();

  /** Send a raw JSON string over the WebSocket. */
  void send_raw_(const std::string &json);

  /** Build and send a JSON message object. */
  void send_json_(JsonDocument &doc);

  /** WebSocket event dispatcher (called from static trampoline). */
  void on_ws_event_(WStype_t type, uint8_t *payload, size_t length);

  /** Decode a base64 string into `screenshot_buf_` and fire callbacks. */
  void handle_screenshot_(const char *b64, size_t b64_len);

  /** Update the status text sensor and log. */
  void set_status_(const std::string &status);

  /** Compute the next reconnect delay (+jitter, capped at 60 s). */
  uint32_t next_reconnect_delay_ms_() const;

  // Trampoline so WebSocketsClient can reach the member callback.
  static void ws_event_trampoline_(WStype_t type, uint8_t *payload, size_t length);
  static BrowserRelayClient *instance_;  // single-instance pointer for trampoline.
};


// ─────────────────────────────────────────────────────────────────────────────
// Trigger
// ─────────────────────────────────────────────────────────────────────────────

class ScreenshotTrigger : public Trigger<uint8_t *, size_t> {
 public:
  explicit ScreenshotTrigger(BrowserRelayClient *parent) {
    parent->add_on_screenshot_callback(
        [this](uint8_t *data, size_t len) { this->trigger(data, len); });
  }
};


// ─────────────────────────────────────────────────────────────────────────────
// Action templates
// ─────────────────────────────────────────────────────────────────────────────

template<typename... Ts>
class NavigateAction : public Action<Ts...>, public Parented<BrowserRelayClient> {
 public:
  TEMPLATABLE_VALUE(std::string, url)
  void play(Ts... x) override { this->parent_->navigate(this->url_.value(x...)); }
};

template<typename... Ts>
class ClickAction : public Action<Ts...>, public Parented<BrowserRelayClient> {
 public:
  TEMPLATABLE_VALUE(int, x)
  TEMPLATABLE_VALUE(int, y)
  TEMPLATABLE_VALUE(std::string, button)
  void play(Ts... x) override {
    this->parent_->click(this->x_.value(x...), this->y_.value(x...), this->button_.value(x...));
  }
};

template<typename... Ts>
class ScrollAction : public Action<Ts...>, public Parented<BrowserRelayClient> {
 public:
  TEMPLATABLE_VALUE(int, delta_x)
  TEMPLATABLE_VALUE(int, delta_y)
  void play(Ts... x) override {
    this->parent_->scroll(this->delta_y_.value(x...), this->delta_x_.value(x...));
  }
};

template<typename... Ts>
class TypeTextAction : public Action<Ts...>, public Parented<BrowserRelayClient> {
 public:
  TEMPLATABLE_VALUE(std::string, text)
  void play(Ts... x) override { this->parent_->type_text(this->text_.value(x...)); }
};

template<typename... Ts>
class KeyPressAction : public Action<Ts...>, public Parented<BrowserRelayClient> {
 public:
  TEMPLATABLE_VALUE(std::string, key)
  void play(Ts... x) override { this->parent_->key_press(this->key_.value(x...)); }
};

template<typename... Ts>
class ConnectAction : public Action<Ts...>, public Parented<BrowserRelayClient> {
 public:
  void play(Ts... x) override { this->parent_->connect_session(); }
};

template<typename... Ts>
class DisconnectAction : public Action<Ts...>, public Parented<BrowserRelayClient> {
 public:
  void play(Ts... x) override { this->parent_->disconnect_session(); }
};

}  // namespace browser_relay
}  // namespace esphome

#endif  // USE_ESP32
